# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=250)),
                ('food_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Food_types')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='food_types',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Types'),
        ),
    ]
